---
# handlers for the haproxy role
- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart rsyslog-haproxy
  service: name=rsyslog state=restarted

- name: reload systemd
  systemd:
    daemon_reload: yes
